### ISSUE TITLE
Restore problem

### ISSUE THREAD

**Issue by gtbu** [DSB/MySQLDumper#27]
When restoring a 230 MB Mwediawiki 1.19 database i get the error
Sql: 
Erweiterte Inserts: 1
Unbekannter SQL-Befehl::

**Comment by DSB** [comment]
You can't see this here since it is escaped as a HTML comment but via email I saw this: 

Sql: < ! -- PMA-SQL-ERROR -- >

This simply means that PhpMyAdmin had a problem while creating the backup. Your backup is broken and incomplete. Of course there is no chance to restore such a backup. That's why also backups should be created using MySQLDumper. Unfortunately most people try MySQLDumper when they are not able to restore their backup created by other tools. I'm sorry - we can't help you in this case.
